# .github/workflows/snake.yml

name: Generate Snake Animation

on:
  # Executa automaticamente a cada 12 horas
  schedule:
    - cron: "0 */12 * * *"
  
  # Permite executar manualmente
  workflow_dispatch:
  
  # Executa em cada push na main
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    
    steps:
      # Checkout do reposit√≥rio
      - name: Checkout
        uses: actions/checkout@v3
      
      # Gera o arquivo SVG da cobra
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: joaz0
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark
            dist/github-snake-light.svg?palette=github-light
      
      # Commit e push dos arquivos gerados
      - name: Push to GitHub
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
